// Optional real-browser smoke test. npm install --no-save playwright; npx playwright install chromium
const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const browser=await chromium.launch({headless:true});try{const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);assert.equal(await page.locator('[role=tab]').count(),5);
for(const name of ['materials','boundaries','solver','results','geometry']){await page.locator('#tab-'+name).click();assert.ok(await page.locator('#'+name).isVisible());}
for(const value of ['0','-1']){await page.locator('#depth').fill(value);assert.equal(await page.locator('#depth').getAttribute('aria-invalid'),'true');for(const id of ['run','save','applyGrid'])assert.ok(await page.locator('#'+id).isDisabled());assert.ok(await page.locator('#validationSummary').isVisible());}
await page.locator('#depth').fill('1');assert.ok(await page.locator('#run').isEnabled());
await page.locator('#tab-materials').click();const conductivity=page.locator('[data-material="0"] [data-key="k"]');const oldK=await conductivity.inputValue();await conductivity.fill('-1');assert.ok(await page.locator('#run').isDisabled());assert.equal(await conductivity.getAttribute('aria-invalid'),'true');await conductivity.fill(oldK);assert.ok(await page.locator('#run').isEnabled());await page.locator('#tab-geometry').click();
await page.locator('#nx').fill('20');await page.locator('#ny').fill('10');await page.locator('#applyGrid').click();assert.match(await page.locator('#gridInfo').textContent(),/200 elements.*231 nodes/);
await page.locator('#tab-materials').click();const slope=page.locator('[data-material="1"] [data-key="alphaSlope"]');assert.equal(await slope.inputValue(),'0.2');
await page.locator('#preset').selectOption('seebeck');await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#badge').textContent==='CONVERGED',null,{timeout:60000});assert.ok(await page.locator('#results').isVisible());assert.match(await page.locator('#spectrum').textContent(),/-1\.00000e-2/);
await page.locator('#preset').selectOption('nonlinear');await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#badge').textContent==='CONVERGED',null,{timeout:120000});assert.equal(await page.locator('#spectrum tr').count(),4);await page.locator('#harmonic').selectOption('3');await page.locator('#field').selectOption('J');
const download=page.waitForEvent('download');await page.locator('#exportResults').click();await download;
await page.locator('#run').click();await page.locator('#cancel').click();assert.ok(await page.locator('#run').isEnabled());await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('Real-browser smoke checks passed.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
