const {test}=require('node:test'),assert=require('node:assert/strict'),TE=require('./load.cjs'),ref=require('./reference_1d.json');
const close=(a,b,tol=1e-7)=>assert.ok(Math.abs(a-b)<tol,`${a} vs ${b}, tolerance ${tol}`),mag=z=>Math.hypot(z.re,z.im),cclose=(a,b,rtol,atol=0)=>assert.ok(Math.hypot(a.re-b.re,a.im-b.im)<atol+rtol*mag(b),JSON.stringify({a,b,rtol,atol}));
function config(nx=8,ny=4){const c=TE.default2D();Object.assign(c,{nx,ny,lx:.001,ly:.001,depth:.001,materialMap:Array(nx*ny).fill(0),mode:'steady'});c.materials=[{name:'test',rho:2000,Cp:500,k:2,sigma:1e5,beta:0,alpha:0,alphaSlope:0}];c.thermal.right={kind:'temperature',value:{bias:300,amplitude:0},h:0};c.electrical.value={bias:.1,amplitude:0};return c;}
function cavity(x,y,Q,omega=0){let re=0,im=0;for(let m=1;m<=101;m+=2)for(let n=1;n<=101;n+=2){const source=16*Q/(Math.PI**2*m*n)*Math.sin(m*Math.PI*x/.001)*Math.sin(n*Math.PI*y/.001),a=2*Math.PI**2*((m/.001)**2+(n/.001)**2),b=omega*1e6;re+=source*a/(a*a+b*b);im-=source*b/(a*a+b*b);}return {re,im};}
function allFixed(c){for(const side of ['left','right','top','bottom'])c.thermal[side]={kind:'temperature',value:300,h:0};return c;}
test('2D mesh volumes and control-volume capacities',()=>{const c=config(),s=TE.from2DConfig(c),m=s.mesh;close(m.volumes.reduce((a,b)=>a+b,0),1e-9,1e-20);close(s.properties(Array(m.n).fill(300)).cap.reduce((a,b)=>a+b,0),.001,1e-13);});
test('manufactured quadratic 2D Poisson solution',()=>{const m=new TE.Mesh2D({nx:10,ny:8,lx:.001,ly:.001,depth:.001}),k=2,coef=1e6,exact=m.x.map((x,i)=>300+coef*(x*x+m.y[i]**2)),fixed=new Map();for(const side of Object.values(m.sides))for(const f of side)fixed.set(f.node,exact[f.node]);const V=TE.graphSolve(m,m.links.map(e=>k*e.A/e.L),Array(m.n).fill(0),m.volumes.map(v=>-4*k*coef*v),fixed);V.forEach((v,i)=>close(v,exact[i],1e-6));});
test('uniform full-contact current, resistance and transverse invariance',()=>{const c=config(),s=TE.from2DConfig(c),T=Array(s.mesh.n).fill(300),b=s.balance(T,0),r=s.snapshot(T,0);close(b.current,.1,1e-12);close(b.terminalVoltage,-.001,1e-10);r.Jx.forEach(v=>close(v,1e5,1e-3));r.Jy.forEach(v=>close(v,0,1e-3));});
test('current in vertical direction uses electrode area correctly',()=>{const c=config();c.electrical.sourceSide='bottom';c.electrical.sinkSide='top';const s=TE.from2DConfig(c),r=s.snapshot(Array(s.mesh.n).fill(300));close(r.current,.1,1e-12);r.Jy.forEach(v=>close(v,1e5,.001));r.Jx.forEach(v=>close(v,0,.001));});
test('partial electrode yields current spreading and conserves current',()=>{const c=config(12,8);c.electrical.sourceRange=[.25,.75];const s=TE.from2DConfig(c),b=s.balance(Array(s.mesh.n).fill(300),0),r=s.snapshot(Array(s.mesh.n).fill(300)),div=Array(s.mesh.n).fill(0);s.mesh.links.forEach((e,i)=>{div[e.a]+=b.I[i];div[e.b]-=b.I[i];});const contacts=new Set([...s.source,...s.sink]);assert.ok(Math.max(...r.Jy.map(Math.abs))>1000);close(s.source.reduce((a,i)=>a+div[i],0),.1,1e-10);close(s.sink.reduce((a,i)=>a+div[i],0),-.1,1e-10);div.forEach((v,i)=>{if(!contacts.has(i))close(v,0,1e-9);});s.source.forEach(i=>close(b.V[i],0,1e-14));s.sink.forEach(i=>close(b.V[i],b.terminalVoltage,1e-14));});
test('multimaterial resistance in series',()=>{const c=config();c.materials.push({...c.materials[0],sigma:1e6});c.materialMap=c.materialMap.map((_,i)=>i%c.nx<c.nx/2?0:1);const s=TE.from2DConfig(c),r=s.snapshot(Array(s.mesh.n).fill(300));close(r.terminalVoltage,-.1*(.0005/1e5+.0005/1e6)/1e-6,1e-10);});
test('material interface capacity uses both regions',()=>{const c=config();c.materials.push({...c.materials[0],rho:4000});c.materialMap=c.materialMap.map((_,i)=>i%c.nx<c.nx/2?0:1);const s=TE.from2DConfig(c),id=2*(c.nx+1)+c.nx/2,p=s.properties(Array(s.mesh.n).fill(300));close(p.cap[id],s.mesh.volumes[id]*1.5e6,1e-15);});
test('Seebeck DC reduces to analytic 1D limit',()=>{const c=config();c.materials[0].alpha=2e-4;c.thermal.right.value.bias=350;c.electrical.kind='open_circuit';const r=TE.run2D(c);close(r.terminalVoltage,-.01,1e-8);r.temperature.forEach((v,i)=>close(v,300+50*(i%(c.nx+1))/c.nx,1e-6));});
test('open circuit can have internal circulating currents in 2D',()=>{const c=config();c.materials.push({...c.materials[0],alpha:2e-4});c.materialMap=c.materialMap.map((_,i)=>Math.floor(i/c.nx)<c.ny/2?0:1);c.electrical.kind='open_circuit';const s=TE.from2DConfig(c),T=s.mesh.x.map(x=>300+50*x/.001),r=s.snapshot(T);close(r.current,0,1e-10);assert.ok(Math.max(...r.Jx.map(Math.abs))>1e4);assert.ok(Math.min(...r.Jx)<-1e4);assert.ok(Math.max(...r.Jx)>1e4);});
test('Joule parabola and energy balance in extruded 1D',()=>{const c=config();c.electrical.value.bias=1;const r=TE.run2D(c);r.temperature.forEach((v,i)=>{const x=i%(c.nx+1)*.001/c.nx;close(v,300+1e7*x*(.001-x)/4,2e-6);});close(r.energyResidual,0,1e-8);});
test('Peltier interface analytical temperature',()=>{const c=config();c.materials[0].alpha=1e-5;c.materials.push({...c.materials[0],alpha:2e-4});c.materialMap=c.materialMap.map((_,i)=>i%c.nx<c.nx/2?0:1);const r=TE.run2D(c),J=1e5,Ti=(2*300/.0005+2*300/.0005+J*J*1e-5*.001/2)/(2/.0005+2/.0005+J*(2e-4-1e-5));close(r.temperature[2*(c.nx+1)+c.nx/2],Ti,2e-6);close(r.energyResidual,0,1e-8);});
test('adiabatic boundary includes Peltier transport',()=>{const c=config();c.materials[0].alpha=2e-4;c.electrical.value.bias=.01;c.thermal.left={kind:'flux',value:0,h:0};const r=TE.run2D(c),J=1e4;close(r.temperature[0],(300+J*J/1e5*.001**2/4)/(1+2e-4*J*.001/2),2e-6);});
test('convection and total energy balance',()=>{const c=config();c.electrical.value.bias=1;for(const side of ['left','right'])c.thermal[side]={kind:'convection',value:300,h:1000};const r=TE.run2D(c);close(r.temperature[0],305,3e-6);close(r.energyResidual,0,1e-8);});
test('genuine 2D Joule solution converges to double sine series',()=>{const errors=[];for(const n of [8,16]){const c=allFixed(config(n,n));c.electrical.value.bias=1;const r=TE.run2D(c),mid=n/2*(n+1)+n/2;errors.push(Math.abs(r.temperature[mid]-300-cavity(.0005,.0005,1e7).re));close(r.energyResidual,0,1e-8);}assert.ok(errors[1]<.35*errors[0]);assert.ok(errors[1]<.002);});
test('2D complex thermal 2ω response matches analytical sine series',()=>{const c=allFixed(config(10,10));c.mode='periodic';c.electrical.value={bias:0,amplitude:1};c.samples=256;const r=TE.run2D(c),mid=5*11+5,expected=cavity(.0005,.0005,5e6,8*Math.PI);cclose(r.harmonics.temperature[2][mid],expected,.03,1e-4);close(r.harmonics.temperature[0][mid].re,300+cavity(.0005,.0005,5e6).re,.002);assert.ok(mag(r.harmonics.temperature[1][mid])<2e-6);});
test('nonlinear 3ω and all temperature harmonics reproduce the 1D solver',()=>{const c=config(10,4);c.mode='periodic';c.materials[0].beta=.01;c.electrical.value={bias:0,amplitude:.2};c.samples=256;const r=TE.run2D(c);for(let n=0;n<=3;n++){cclose(r.harmonics.terminalVoltage[n],ref.voltage[n],.008,2e-11);for(let i=0;i<=10;i++)cclose(r.harmonics.temperature[n][2*11+i],ref.temperature[n][i],.008,2e-7);}});
test('invalid grid, overlapping electrodes and conflicting corners fail',()=>{assert.throws(()=>new TE.Mesh2D({nx:1,ny:2,lx:1,ly:1}));const c=config();c.electrical.sinkSide='left';assert.throws(()=>TE.from2DConfig(c));c.electrical.sinkSide='right';c.thermal.top={kind:'temperature',value:350,h:0};assert.throws(()=>TE.run2D(c),/corner/);});
test('steady unanchored and insufficient periodic cycles are rejected',()=>{const c=config();for(const side of Object.keys(c.thermal))c.thermal[side]={kind:'flux',value:0,h:0};assert.throws(()=>TE.run2D(c),/anchor/);const s=TE.from2DConfig(config());assert.throws(()=>s.solvePeriodic(1e5,{samples:32,maxPeriods:2,minPeriods:2}),/not reached/);});
test('Thomson term agrees with analytical temperature-dependent Seebeck case',()=>{const c=config(20,4);c.materials[0].alpha=T=>.002*Math.log(T/300);c.electrical.value.bias=1;c.thermal.right.value.bias=350;const s=TE.from2DConfig(c),r=s.solveSteady(),a=1000,Q=1e7,bJ=2000;let error=0;for(let i=0;i<=20;i++){const x=.001*i/20,exact=300+(50-Q*.001/bJ)*Math.expm1(a*x)/Math.expm1(a*.001)+Q*x/bJ;error=Math.max(error,Math.abs(r.temperature[2*21+i]-exact));}assert.ok(error<.008);});
test('vertical imposed heat flux has the correct outward sign',()=>{const c=config();c.electrical.kind='open_circuit';c.thermal.left={kind:'flux',value:0,h:0};c.thermal.right={kind:'flux',value:0,h:0};c.thermal.bottom={kind:'temperature',value:300,h:0};c.thermal.top={kind:'flux',value:-1000,h:0};const r=TE.run2D(c);r.temperature.forEach((v,i)=>close(v,300+1000*Math.floor(i/(c.nx+1))*.001/c.ny/2,1e-6));close(r.energyResidual,0,1e-8);});
test('2D time-step refinement exhibits second-order convergence',()=>{const values=[];for(const samples of [64,128,256]){const c=allFixed(config(6,6));c.mode='periodic';c.samples=samples;c.electrical.value={bias:0,amplitude:1};const r=TE.run2D(c);values.push(r.harmonics.temperature[2][3*7+3]);}const d=(a,b)=>Math.hypot(a.re-b.re,a.im-b.im);assert.ok(d(values[1],values[2])<.4*d(values[0],values[1]));});

test('Ny=1: nonlinear 3ω and all temperature harmonics reproduce the 1D solver',()=>{const c=config(10,1);c.mode='periodic';c.materials[0].beta=.01;c.electrical.value={bias:0,amplitude:.2};c.samples=256;const r=TE.run2D(c);for(let n=0;n<=3;n++){cclose(r.harmonics.terminalVoltage[n],ref.voltage[n],.008,2e-11);for(let i=0;i<=10;i++)cclose(r.harmonics.temperature[n][i],ref.temperature[n][i],.008,2e-7);}});

test('Ny=1: Seebeck DC reduces to analytic 1D limit',()=>{const c=config(8,1);c.materials[0].alpha=2e-4;c.thermal.right.value.bias=350;c.electrical.kind='open_circuit';const r=TE.run2D(c);close(r.terminalVoltage,-.01,1e-8);r.temperature.forEach((v,i)=>close(v,300+50*(i%(c.nx+1))/c.nx,1e-6));});

test('Ny=1: Peltier interface analytical temperature',()=>{const c=config(8,1);c.materials[0].alpha=1e-5;c.materials.push({...c.materials[0],alpha:2e-4});c.materialMap=c.materialMap.map((_,i)=>i%c.nx<c.nx/2?0:1);const r=TE.run2D(c),J=1e5,Ti=(2*300/.0005+2*300/.0005+J*J*1e-5*.001/2)/(2/.0005+2/.0005+J*(2e-4-1e-5));close(r.temperature[c.nx/2],Ti,2e-6);close(r.energyResidual,0,1e-8);});
